---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
    channel: "eslint-2"
  fixme:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc"
      standard: "PSR1,PSR2"
    # checks:
    #   PSR1 Classes ClassDeclaration MissingNamespace:
    #     enabled: false
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
          enabled: false
  radon:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - tests/
exclude_paths:
# - config/
# - tests/
# - "**.spec.php"
- tests/__tests__
